### PR TITLE
Order emissions data by Name and Budget

### PR DESCRIPTION
**Pull request by natstar93**
## Changes
- Change emissions data JSON object to array of objects for easier sorting
- Pass sorted emissionsData into updateCountries function as a variable instead of relying on global emissions variable
- Enable sorting by country name (alphabetical) and budget (ascending/descending value)
- Render World emissions data at the top of the emissions table and exclude from sorting
- A bit of styling (chevrons, world data row)

Partially completes issue #12 Will work on another PR for the searching stuff

## Some thoughts I had
This is a really cool and informative project :) Have you got a plan to serve and host it somewhere? Happy to help with that if needed! Also if you're looking for more people to help, I found your project through the climate change section on [Hacktoberfest](https://hacktoberfest.digitalocean.com) which is nearly over but [24 Pull Requests](https://24pullrequests.com) is coming up and they might promote some projects on there when it starts in December. I can also share the project with a pretty active community called [Climate Action Tech](https://climateaction.tech/) if you like.

One thing I thought when looking at the emissions table is that it doesn't explain what `Total Budget [tons]` means, so it might be worth changing that to  `Total Budget 1/1/2018 [tons]`, or something. It might be good to explain how the total budget is calculated too. Also some of the countries are missing data so it's showing up as 0.

### CODE REVIEW

**Comment by moredatapls** [comment]
Hi! Thank you for your PR and the feedback! Could you turn this into two issues so we can discuss there? I.e. one about the "Promotion of the project" and one about the "Budget calculation" and just put your text there.

Will review the PR later today :)

**Comment by moredatapls** [comment]
Also, this probably conflicts with #13 once merged, so this PR might need a rebase then

**Comment by moredatapls** [comment]
As predicted, there are merge conflicts now. @natstar93, could you rebase and resolve them? Thank you!

**Comment by natstar93** [comment]
@moredatapls I've fixed the conflict and opened a few issues ;)

**Review by moredatapls — APPROVED** [review]

**Pull request merged**
